export const ROOM_TYPES = [
  {
    id: "salon",
    label: "Salon",
    displayLabel: "Salon / Pièce à vivre",
    description: "Canapé, fauteuil, table basse, TV",
  },
  {
    id: "chambre",
    label: "Chambre",
    displayLabel: "Chambre",
    description: "Lit double, tables de nuit",
  },
  {
    id: "cuisine",
    label: "Cuisine",
    displayLabel: "Cuisine",
    description: "Îlot, tabourets, coin repas",
  },
  {
    id: "salle_a_manger",
    label: "Salle à manger",
    displayLabel: "Salle à manger",
    description: "Table, chaises",
  },
  {
    id: "bureau",
    label: "Bureau",
    displayLabel: "Bureau / Home office",
    description: "Bureau, chaise, lampe",
  },
  {
    id: "salle_de_bain",
    label: "Salle de bain",
    displayLabel: "Salle de bain",
    description: "Textiles, plante décorative",
  },
  {
    id: "entree",
    label: "Entrée",
    displayLabel: "Entrée / Hall",
    description: "Console, miroir, banc",
  },
  {
    id: "couloir",
    label: "Couloir",
    displayLabel: "Couloir",
    description: "Console étroite, miroir",
  },
  {
    id: "chambre_enfant",
    label: "Chambre enfant",
    displayLabel: "Chambre d'enfant",
    description: "Lit simple, bureau, étagère",
  },
  {
    id: "chambre_bebe",
    label: "Chambre bébé",
    displayLabel: "Chambre bébé / Nursery",
    description: "Lit bébé, commode, fauteuil",
  },
  {
    id: "chambre_ado",
    label: "Chambre ado",
    displayLabel: "Chambre d'adolescent",
    description: "Lit, bureau d'étude, bibliothèque",
  },
  {
    id: "chambre_invites",
    label: "Chambre invités",
    displayLabel: "Chambre d'amis",
    description: "Lit queen, tables de nuit",
  },
  {
    id: "suite_parentale",
    label: "Suite parentale",
    displayLabel: "Suite parentale",
    description: "Lit king, banc de bout de lit",
  },
  {
    id: "dressing",
    label: "Dressing",
    displayLabel: "Dressing / Walk-in",
    description: "Banc ottoman, miroir pied",
  },
  {
    id: "bibliotheque",
    label: "Bibliothèque",
    displayLabel: "Bibliothèque / Salon lecture",
    description: "Fauteuil cuir, lampe de lecture",
  },
  {
    id: "salon_tv",
    label: "Salon TV",
    displayLabel: "Salon TV / Den",
    description: "Canapé d'angle, meuble TV",
  },
  {
    id: "salle_detente",
    label: "Salle détente",
    displayLabel: "Salle de détente",
    description: "Fauteuils lounge, table basse",
  },
  {
    id: "cinema",
    label: "Cinéma maison",
    displayLabel: "Home cinéma",
    description: "Grand canapé, écran TV",
  },
  {
    id: "salle_jeux",
    label: "Salle de jeux",
    displayLabel: "Salle de jeux",
    description: "Billard ou baby-foot, tabourets",
  },
  {
    id: "studio",
    label: "Studio",
    displayLabel: "Studio / T1",
    description: "Canapé-lit, table, bureau compact",
  },
  {
    id: "cuisine_ouverte",
    label: "Cuisine ouverte",
    displayLabel: "Cuisine ouverte sur séjour",
    description: "Îlot, canapé, table basse",
  },
  {
    id: "open_space",
    label: "Open space",
    displayLabel: "Open space / Loft",
    description: "Séjour, salle à manger, cuisine",
  },
  {
    id: "mezzanine",
    label: "Mezzanine",
    displayLabel: "Mezzanine",
    description: "Fauteuil, table de lecture",
  },
  {
    id: "buanderie",
    label: "Buanderie",
    displayLabel: "Buanderie / Laverie",
    description: "Paniers, plante décorative",
  },
  {
    id: "salle_eau",
    label: "Salle d'eau",
    displayLabel: "Salle d'eau / WC",
    description: "Serviettes, petite plante",
  },
  {
    id: "spa",
    label: "Spa",
    displayLabel: "Spa / Bien-être",
    description: "Chaise longue, serviettes roulées",
  },
  {
    id: "cave",
    label: "Cave à vin",
    displayLabel: "Cave à vin",
    description: "Table de dégustation, casier bouteilles",
  },
  {
    id: "sous_sol",
    label: "Sous-sol",
    displayLabel: "Sous-sol aménagé",
    description: "Canapé, table basse, media",
  },
  {
    id: "grenier_amenage",
    label: "Grenier",
    displayLabel: "Grenier aménagé",
    description: "Banquette, bureau, étagère",
  },
  {
    id: "garage",
    label: "Garage",
    displayLabel: "Garage",
    description: "Établi, tabourets, rangement vélo",
  },
  {
    id: "atelier",
    label: "Atelier",
    displayLabel: "Atelier / Studio créatif",
    description: "Grand plan de travail, tabourets",
  },
  {
    id: "salle_sport",
    label: "Salle de sport",
    displayLabel: "Salle de sport maison",
    description: "Tapis yoga, banc, miroir",
  },
  {
    id: "terrasse",
    label: "Terrasse",
    displayLabel: "Terrasse / Patio",
    description: "Salon de jardin, table repas",
  },
  {
    id: "balcon",
    label: "Balcon",
    displayLabel: "Balcon",
    description: "Table bistro, deux chaises",
  },
  {
    id: "veranda",
    label: "Véranda",
    displayLabel: "Véranda / Véranda vitrée",
    description: "Fauteuil rotin, table d'appoint",
  },
  {
    id: "loggia",
    label: "Loggia",
    displayLabel: "Loggia couverte",
    description: "Transat, table d'appoint, olivier",
  },
  {
    id: "serre",
    label: "Serre",
    displayLabel: "Serre / Jardin d'hiver",
    description: "Bistro fer forgé, plantes en pot",
  },
  {
    id: "pool_house",
    label: "Pool house",
    displayLabel: "Pool house",
    description: "Canapé extérieur, transats",
  },
  {
    id: "exterieur",
    label: "Extérieur",
    displayLabel: "Espace extérieur / Jardin",
    description: "Salon de jardin, brasero, repas",
  },
  {
    id: "palier",
    label: "Palier",
    displayLabel: "Palier d'escalier",
    description: "Console, miroir mural",
  },
];
